### ISSUE TITLE
[naming] secret lair finish deck property

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtg-sealed-content#108]
In SLD there are a bunch of products that differ by the finish of their cards, namely etched, foil, and nonfoil

the problem is that the name doesn't really follow this schema, such as

-                "name": "Secret Lair Special Guest Junji Ito English",
-                "name": "Secret Lair Special Guest Junji Ito English Foil Etched Edition",

-          "name": "Secret Lair Artist Series Victor Adame Minguez",
-          "name": "Secret Lair Artist Series Victor Adame Minguez Foil",

"nonfoil" is often missing
I wonder if we should either standardize SLD names too or add a field that indicates whether the product contains only foil or nonfoil

**Comment by axxroytovu** [comment]
I've been trying to standardize them to use blank as nonfoil and drop the `Edition` as unnecessary. 

`Secret Lair {Drop/Bundle} {Product Name} {none/Foil/Etched Foil/etc.}`

**Comment by kodawah** [comment]
ah cool, may i suggest to keep "Non-foil" instead of None, for ease of parsing?

**Comment by kodawah** [comment]
proposal

```
  Secret Lair Theros Stargazing Bundle Full: 
  Secret Lair Theros Stargazing Vol I Heliod:
  Secret Lair Theros Stargazing Vol II Thassa:
  Secret Lair Theros Stargazing Vol III Erebos:
  Secret Lair Theros Stargazing Vol IV Purphoros:
  Secret Lair Theros Stargazing Vol V Nylea:
```
