### ISSUE TITLE
Update booster tags

### ISSUE THREAD

**Issue by axxroytovu** [mtgjson/mtg-sealed-content#117]
Draft Tag:
- [x] The Lost Caverns of Ixalan (LCI)
- [x] Wilds of Eldraine (WOE)
- [x] Commander Masters (CMM)
- [x] March of the Machine (MOM)
- [x] Phyrexia: All Will Be One (ONE)
- [x] Dominaria Remastered (DMR)
- [x] The Brothers' War (BRO)
- [x] Unfinity (UNF)
- [x] Dominaria United (DMU)
- [x] Double Masters 2022 (2X2)
- [x] Commander Legends: Battle for Baldur's Gate (CLB)
- [x] Streets of New Capenna (SNC)
- [x] Kamigawa: Neon Dynasty (NEO)
- [x] Innistrad: Double Feature (DBL)
- [x] Innistrad: Crimson Vow (VOW)
- [x] Innistrad: Midnight Hunt (MID)
- [x] Adventures in the Forgotten Realms (AFR)
- [x] Modern Horizons 2 (MH2)
- [x] Strixhaven: School of Mages (STX)
- [x] Time Spiral Remastered (TSR)
- [x] Kaldheim (KHM)
- [x] Commander Legends (CMR)
- [x] Zendikar Rising (ZNR)
- [x] Double Masters (2XM)
- [x] Core Set 2021 (M21)
- [x] Ikoria: Lair of Behemoths (IKO)
- [x] Theros Beyond Death (THB)
- [x] Mystery Booster Pack Retail Edition (MB1)
- [x] Throne of Eldraine (ELD)
- [x] Core Set 2020 (M20)
- [x] Modern Horizons (MH1)
- [x] War of the Spark (WAR)
- [x] Ravnica Allegiance (RNA)
- [x] Ultimate Masters (UMA)
- [x] Guilds of Ravnica (GRN)
- [x] Core Set 2019 (M19)
- [x] Battlebond (BBD)
- [x] Dominaria (DOM)
- [x] Masters 25 (A25)
- [x] Rivals of Ixalan (RIX)
- [x] Unstable (UST)
- [x] Iconic Masters (IMA)
- [x] Ixalan (XLN)
- [x] Hour of Devastation (HOU)
- [x] Amonkhet (AKH)
- [x] Modern Masters 2017 (MM3)
- [x] Aether Revolt (AER)
- [x] Kaladesh (KLD)
- [x] Conspiracy: Take the Crown (CN2)
- [x] Eldritch Moon (EMN)
- [x] Eternal Masters (EMA)
- [x] Shadows over Innistrad (SOI)
- [x] Oath of the Gatewatch (OGW)
- [x] Battle for Zendikar (BFZ)
- [x] Magic Origins (ORI)
- [x] Modern Masters 2015 (MM2)
- [x] Tempest Remastered (TPR)
- [x] Dragons of Tarkir (DTK)
- [x] Fate Reforged (FRF)
- [x] Khans of Tarkir (KTK)
- [x] Magic 2015 (M15)
- [x] Vintage Masters (VMA)
- [x] Conspiracy (CNS)
- [x] Journey into Nyx (JOU)
- [x] Born of the Gods (BNG)
- [x] Theros (THS)
- [x] Magic 2014 (M14)
- [x] Modern Masters (MMA)
- [x] Dragon's Maze (DGM)
- [x] Gatecrash (GTC)
- [x] Return to Ravnica (RTR)
- [x] Magic 2013 (M13)
- [x] Avacyn Restored (AVR)
- [x] Dark Ascension (DKA)
- [x] Innistrad (ISD)
- [x] Magic 2012 (M12)
- [x] New Phyrexia (NPH)
- [x] Mirrodin Besieged (MBS)
- [x] Masters Edition IV (ME4)
- [x] Scars of Mirrodin (SOM)
- [x] Magic 2011 (M11)
- [x] Rise of the Eldrazi (ROE)
- [x] Worldwake (WWK)
- [x] Zendikar (ZEN)
- [x] Masters Edition III (ME3)
- [x] Magic 2010 (M10)
- [x] Alara Reborn (ARB)
- [x] Conflux (CON)
- [x] Shards of Alara (ALA)
- [x] Masters Edition II (ME2)
- [x] Eventide (EVE)
- [x] Shadowmoor (SHM)
- [x] Morningtide (MOR)
- [x] Lorwyn (LRW)
- [x] Masters Edition (ME1)
- [x] Tenth Edition (10E)
- [x] Future Sight (FUT)
- [x] Planar Chaos (PLC)
- [x] Time Spiral (TSP)
- [x] Coldsnap (CSP)
- [x] Dissension (DIS)
- [x] Guildpact (GPT)
- [x] Ravnica: City of Guilds (RAV)
- [x] Ninth Edition (9ED)
- [x] Saviors of Kamigawa (SOK)
- [x] Betrayers of Kamigawa (BOK)
- [x] Unhinged (UNH)
- [x] Champions of Kamigawa (CHK)
- [x] Fifth Dawn (5DN)
- [x] Darksteel (DST)
- [x] Mirrodin (MRD)
- [x] Eighth Edition (8ED)
- [x] Scourge (SCG)
- [x] Legions (LGN)
- [x] Onslaught (ONS)
- [x] Judgment (JUD)
- [x] Torment (TOR)
- [x] Odyssey (ODY)
- [x] Apocalypse (APC)
- [x] Seventh Edition (7ED)
- [x] Planeshift (PLS)
- [x] Invasion (INV)
- [x] Prophecy (PCY)
- [x] Nemesis (NEM)
- [x] Mercadian Masques (MMQ)
- [x] Urza's Destiny (UDS)
- [x] Classic Sixth Edition (6ED)
- [x] Urza's Legacy (ULG)
- [x] Urza's Saga (USG)
- [x] Unglued (UGL)
- [x] Exodus (EXO)
- [x] Stronghold (STH)
- [x] Tempest (TMP)
- [x] Weatherlight (WTH)
- [x] Fifth Edition (5ED)
- [x] Visions (VIS)
- [x] Mirage (MIR)

Default Tag:
- [ ] 30th Anniversary Edition (30A)
- [ ] Starter 1999 (S99)
- [ ] Portal Three Kingdoms (PTK)
- [ ] Portal Second Age (P02)
- [ ] Portal (POR)
- [ ] Alliances (ALL)
- [ ] Homelands (HML)
- [ ] Chronicles (CHR)
- [ ] Ice Age (ICE)
- [ ] Fourth Edition (4ED)
- [ ] Fallen Empires (FEM)
- [ ] The Dark (DRK)
- [ ] Legends (LEG)
- [ ] Revised Edition (3ED)
- [ ] Antiquities (ATQ)
- [ ] Arabian Nights (ARN)
- [ ] Unlimited Edition (2ED)
- [ ] Limited Edition Beta (LEB)
- [ ] Limited Edition Alpha (LEA)

Other Tag:
- [x] March of the Machine: The Aftermath Epilogue Booster (MAT)

**Comment by kodawah** [comment]
@axxroytovu what's left? :-)
