### ISSUE TITLE
card_to_product: incorrect finish picked

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtg-sealed-content#120]
There are a couple of edge cases in which a card with a missing "etched" status from the preconstructed repo will be reported as "foil" in mtgjson, which will lead to the source product be unretrievable

example
* https://scryfall.com/card/sld/305/ravenous-chupacabra this cards Nonfoil and Etched as its finish, so a single number will mark both finishes
* https://github.com/taw/magic-preconstructed-decks/blob/732d9d1cb8408f97123d8fe57129b8e3ac9f2995/data/sld/sld/Crocodile%20Jacksons%20Monstrous%20Menagerie%20etched.txt will list the cards as "foil" instead of etched
* the script will use "foil" as input finish
* allprintings will end up 
```json
          "sourceProducts": {
            "foil": [
              "fe2703b6-2c82-5d41-9f1e-8adacebc50b9"
            ],
            "nonfoil": [
              "cff258e1-2e9a-510b-99b4-ded71d7615b3"
            ]
          },
```
* end user will not be able to retrieve the "foil" uuid because there is no "foil" tag in the finishes array

i took a brief look at the decklists and it seems like etched property is never reported
do we want to work around it by checking the product title (if it contains `etched`) or validate finish properties before using them? or should we just upstream this?

**Comment by axxroytovu** [comment]
I think there are two things that need to happen:

- The etched finish needs to come from the decklist repo which currently doesn't support that
- I need to review our scripts to make sure that they support the etched finish. 

Can you put in the upstream issue?

**Comment by kodawah** [comment]
I sent a PR for the missing tags
