### ISSUE TITLE
consider using String instead of int to reprsent Contents.Card.Number

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtg-sealed-content#20]
this is not yet the case, but it could happen that the number of a card contains letters or other symbols
as a precaution, and consistency with the collector number type elsewhere, I'd suggest to change the `number` type from int to string

```json
            "card": [
              {
                "foil": false,
                "name": "Thorn Elemental",
                "number": 11,
                "set": "o90p",
                "uuid": "6a4a698e-42d7-54ec-97b1-aa7cc54f2bd5"
              }
            ],
```

**Comment by axxroytovu** [comment]
Card numbers could be either int or string depending on need. They've been unified as strings.
