### ISSUE TITLE
consider changing the Content.Variable data type

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtg-sealed-content#22]
the various array types in Contents are used to represent the contents of a sealed product - except for `variable` which is a type used for when multiple different combinations of contents can be found randomly in the same product. In order to process correctly the variable array one needs to pick a single element of the array and discard the rest

this is a semantic break in my opinion, and I would propose a different approach that stays in line with the other types

instead of doing
```json
            "variable": [
              {
                "card_count": 60,
                "deck": [
                  {
                    "name": "Amonkhet Welcome Deck - White",
                    "set": "w17"
                  },
                  {
                    "name": "Amonkhet Welcome Deck - Blue",
                    "set": "w17"
                  }
                ]
              },
              {
                "card_count": 60,
                "deck": [
                  {
                    "name": "Amonkhet Welcome Deck - White",
                    "set": "w17"
                  },
                  {
                    "name": "Amonkhet Welcome Deck - Black",
                    "set": "w17"
                  }
                ]
              },
            ]
```
we could do
```json
            "variable": [
              {
                "card_count": 60,
                "configs": [ 
                   "deck1": {
                      {
                        "name": "Amonkhet Welcome Deck - White",
                        "set": "w17"
                      },
                      {
                        "name": "Amonkhet Welcome Deck - Blue",
                        "set": "w17"
                      }
                   },
                "deck2": {
                  {
                    "name": "Amonkhet Welcome Deck - White",
                    "set": "w17"
                  },
                  {
                    "name": "Amonkhet Welcome Deck - Black",
                    "set": "w17"
                  }
                }
                ]
              },
            ]
```

and so on

in this way, whenever the `variable` type is found during processing of the Contents array, it will be possible to pick an item at random of the inner `configs` child, and only process that, which is similar to the other Contents type

**Comment by axxroytovu** [comment]
I already moved the card count out of the variable section wherever I can, so if you can point me at that section I'll fix that.

So your proposal is:

```json
"variable": [ "config1", "config2" ]
```
vs
```json
"variable": [ {"configs": [ "config1", "config2" ] } ]
```

There isn't really another keyword to add, so it would literally be increasing the depth without adding any additional information. I don't really see the point in doing this? Maybe I'm missing something.

**Comment by kodawah** [comment]
> I already moved the card count out of the variable section wherever I can, so if you can point me at that section I'll fix that.

that's from the w17 decks in amokhet

> So your proposal is: "variable": [ {"configs": [ "config1", "config2" ] } ]

correct

> There isn't really another keyword to add, so it would literally be increasing the depth without adding any additional information. I don't really see the point in doing this? Maybe I'm missing something.

This is more about preserving the array semantics rather than adding information. Every other Contents type mean "add this element to determine the contents of this product", while this is conveying "don't add every element of this array, but pick one and skip the rest" which requires downstream users to add custom processing for this specific type as well as extra documentation effort for this single element. I know this is going to be an array of just a single type, but it's honestly not a big deal IMO as it lets the whole Contents type to be unmarshaled as a map/dictionary of array of types.
