### ISSUE TITLE
2XM box topper sheet is missing

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtg-sealed-content#23]
apologies if it's already known but the sheet to generate a `Double Masters Box Topper Pack` (f65ce337-cb3f-5f83-91ab-0f095d79020b) seems to be missing from the `Booster` entry

**Comment by axxroytovu** [comment]
I've been adding these missing booster to taw's code as I find them. Fix included here: https://github.com/taw/magic-search-engine/pull/256
