### ISSUE TITLE
MB2 booster name (and validation for booster existence)

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtg-sealed-content#266]
The booster type here is `draft` but in mtgjson, SealedProduct the `Mystery Booster 2 Booster Pack` refers to the booster as `default`.

We could just switch the booster name to fix this case, but I think it would be nice if we could add the booster name validation while importing mtgjson data

**Comment by axxroytovu** [comment]
It already does validation, I just didn't notice the error since it's buried in all the other issues.

https://github.com/mtgjson/mtg-sealed-content/blob/c6ce8e4fde0440ecda24c9dea2cb41595a25e49c/status.txt#L134

**Comment by kodawah** [comment]
hmm i wonder if it should be a hard stop instead of silently failing
