### ISSUE TITLE
SLD variable bonus card should get mapped

### ISSUE THREAD

**Issue by axxroytovu** [mtgjson/mtg-sealed-content#50]
Lots of work, but we could use the `variable.card` object to better represent the SLD bonus cards.

**Comment by kodawah** [comment]
for future reference, these are good data sources https://www.magiclibrarities.net/1299-rarities-secret-lair-drop-series-promos-english-cards-index.html and https://mtg.fandom.com/wiki/Secret_Lair#Bonus_cards

**Comment by kodawah** [comment]
this is already kinda implemented by looking at the Sideboard of the magic-contrstructed-deck repositories, do we need more?

**Comment by kodawah** [comment]
thinking about it some more, i'm starting to believe that the right place for the bonus card is in the product description, not the decklist - this placement would facilitate describing the sets with a variable bonus card too

**Comment by axxroytovu** [comment]
Fixed with https://github.com/mtgjson/mtg-sealed-content/pull/195
