### ISSUE TITLE
Challenger decks are duplicated in the Challenger Decks 2018 edition

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtg-sealed-content#89]
>  Pioneer Challenger Deck 2021 - Mono Red Burn 

and

>  Pioneer Challenger Deck 2021 Mono Red Burn 

are the same deck but they are found in "Pioneer Challenger Decks 2021" and "Challenger Decks 2018" editions respectively

**Comment by axxroytovu** [comment]
This should be resolved already. The contents need to get fixed but I went through and moved all the product references to the correct set code.

**Comment by axxroytovu** [comment]
Confirmed that other challenger decks are no longer appearing in https://mtgjson.com/api/v5/Q01.json

Deck contents are still missing, will leave this issue open until those get resolved.
