### ISSUE TITLE
Standardize name schemes

### ISSUE THREAD

**Issue by kodawah** [mtgjson/mtg-sealed-content#90]
There are a few categories that could benefit some naming standardization

for example, the "gift bundle" words sometimes are swapped, like below, and "edition" is randomly applied

> Innistrad Crimson Vow Gift Bundle Case 
> Adventures in the Forgotten Realms Bundle Gift Edition 

similarly we have a lot of "set of X" when what really are Case boxes

> Wilds of Eldraine Commander Deck Case 
> March of the Machine Commander Decks - Set of 5 

while we could fix the outliers manually i feel like we should design something that automatically could handle these names in the future

edit: also "foil etched" and "etched foil" sets

**Comment by axxroytovu** [comment]
I want to tie this to the product category improvements here: https://github.com/mtgjson/mtgjson/issues/1139

Having consistent categories means consistent naming conventions within categories.

**Comment by kodawah** [comment]
sounds good, should we close this one or keep it open until we get to it?

**Comment by axxroytovu** [comment]
Keep them both open. Once we have clear categories then we need to follow up with consistent naming.

**Comment by kodawah** [comment]
could you make a PR and mark it as draft? in this way people can start reviewing on the PR itself

if i understand correctly you're going for `{edition} {product type} {name} {extras}` as naming scheme?

**Comment by axxroytovu** [comment]
It varies by category.

Booster pack/box/case: `{set} {subtype [optional]} Booster {pack/box/case}` e.g. `The Brothers' War Jumpstart Booster Pack`
Deck or Multi Deck: `{set} {subtype} Deck {deck name}` e.g. `Amonkhet Planeswalker Deck Gideon`
Deck Box: `{set} {subtype} Deck Display`
Box Set: `{set [optional]} {product name}` e.g. `Anthologies` or `Secret Lair {product name}`
Everything else: `{set} {subtype} [identifier]` e.g. `Adventures in the Forgotten Realms Gift Bundle`, `Battle for Zendikar Prerelease Pack`, or `Commander 2013 Commander Decks Set of 5`

**Comment by kodawah** [comment]
interesting, this would be very valuable documentation information

**Comment by ZeldaZach** [comment]
cc @staghouse

**Comment by kodawah** [comment]
@axxroytovu just thought of something, are we going to drop the language from the product name or keep it?
If we opt to keep it i think it should go after set name before product type, like "the dark italian booster box"

**Comment by axxroytovu** [comment]
@kodawah please review https://github.com/mtgjson/mtg-sealed-content/pull/97

**Comment by axxroytovu** [comment]
> @axxroytovu just thought of something, are we going to drop the language from the product name or keep it?
> If we opt to keep it i think it should go after set name before product type, like "the dark italian booster box"

I don't have strong feelings, but my initial feeling on this is that I'd prefer to put the language at the end. That way "Legends Booster Box" and "Legends Booster Box Italian" are next to each other when sorting alphabetically.

**Comment by kodawah** [comment]
the "common" edition name is "Legends Italian" tho (i say common because there isn't an official edition, but things like BCHR (Chronicles Japanese) keep language close together.

also alphabetically-wise I think you'd rather group products like so

Legends Booster Box
Legends Booster Pack
Legends Italian Booster Box
Legends Italian Booster Pack

instead of

Legends Booster Box
Legends Booster Box Italian
Legends Booster Pack
Legends Booster Pack Italian

**Comment by kodawah** [comment]
anything left here? :-)

**Comment by axxroytovu** [comment]
Just the eternal pit that is secret lairs. Everything else should be standardized. If you find any lingering products let me know and I can go in and fix them.

**Comment by axxroytovu** [comment]
Secret lairs should be done at this point. Remaining product name fixes:

- [ ] Remove dashes
- [ ] Standardize theme booster (pack)
- [ ] M19 and G18 both have "2018 gift pack"
- [ ] commander decks
  - [ ] AFC
  - [ ] 40K
  - [ ] KHC
- [ ] DPA decks?
- [ ] DTK & MD1 event deck missing name
- [ ] PC2 missing "Planechase Deck"
- [ ] PTC naming doesn't match W97-W04

**Comment by axxroytovu** [comment]
Any other inconsistencies let me know and they can get fixed one by one
